## Evaluation Notebook

In [35]:
import joblib
import pandas as pd
import sklearn

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [13]:
print("Joblib version:", joblib.__version__)
print("scikit-learn version:", sklearn.__version__)
print("pandas version:", pd.__version__)

Joblib version: 1.6.0
scikit-learn version: 1.6.1
pandas version: 3.0.5

In [37]:
# Import the joblib (startup model pipeline) and save it to a variable
model = joblib.load('startup_model_v1.joblib')

In [16]:
# Load the test data from the CSV file into a pandas DataFrame
df = pd.read_csv('data/startup_success_dataset.csv')

In [29]:
print("rows:", df.shape[0], "\n"
      "columns:", df.shape[1])

df.head()

rows: 100000
columns: 11

,funding_rounds,founder_experience_years,team_size,market_size_billion,product_traction_users,burn_rate_million,revenue_million,investor_type,sector,founder_background,outcome
0,4,13,58,48.225483,594843,18.519211,1.483962e+06,tier2_vc,Health,academic,IPO
1,1,6,221,31.532647,393020,14.298149,8.620568e+05,tier2_vc,Fintech,first_time,Failure
2,3,5,247,4.969722,27636,20.447567,9.726169e+04,none,SaaS,first_time,Failure
3,3,14,229,3.084209,235376,8.177417,1.145785e+06,none,Ecommerce,ex_bigtech,Acquisition
4,1,17,235,13.818188,391765,4.879792,8.608949e+05,none,Health,first_time,Acquisition

In [33]:
# Drop the target from the dataset and save it to a separate variable.
X = df.drop('outcome', axis = 1)
y = df['outcome']

,funding_rounds,founder_experience_years,team_size,market_size_billion,product_traction_users,burn_rate_million,revenue_million,investor_type,sector,founder_background
0,4,13,58,48.225483,594843,18.519211,1.483962e+06,tier2_vc,Health,academic
1,1,6,221,31.532647,393020,14.298149,8.620568e+05,tier2_vc,Fintech,first_time
2,3,5,247,4.969722,27636,20.447567,9.726169e+04,none,SaaS,first_time
3,3,14,229,3.084209,235376,8.177417,1.145785e+06,none,Ecommerce,ex_bigtech
4,1,17,235,13.818188,391765,4.879792,8.608949e+05,none,Health,first_time
...,...,...,...,...,...,...,...,...,...,...
99995,1,10,189,38.766348,261932,7.945616,1.005687e+06,tier1_vc,Ecommerce,serial_founder
99996,1,15,39,49.983039,355153,93.223490,1.627273e+06,none,AI,first_time
99997,0,22,215,3.086470,606292,12.832589,1.967245e+06,tier1_vc,Health,academic
99998,4,24,231,10.815435,277717,28.205609,2.757053e+05,angel,Crypto,ex_bigtech
99999,2,9,286,9.505618,227192,24.351561,1.018080e+06,tier1_vc,AI,first_time

In [34]:
# Split the data into training and testing sets. Stratify the split to make sure the class distribution between sets is always the same.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42, stratify = y
)

In [36]:
y_prediction = model.predict(X_test)
print(classification_report(y_test, y_prediction))

              precision    recall  f1-score   support

 Acquisition       0.72      0.66      0.69      8467
     Failure       0.76      0.83      0.80     11122
         IPO       0.65      0.27      0.38       411

    accuracy                           0.74     20000
   macro avg       0.71      0.58      0.62     20000
weighted avg       0.74      0.74      0.74     20000